### ISSUE TITLE
How about a 64 bit library?

### ISSUE THREAD

**Issue by krundt** [bmitov/IGDIPlus#1]
The "cbgdiplus.lib" in Lib is obviously for 32 bit only.  The file "cbgdiplus.a" is missing.
{$IFDEF CPUX64}
{$HPPEMIT '#pragma link "cbgdiplus.a"'}
{$ELSE}
{$HPPEMIT '#pragma link "cbgdiplus.lib"'}
{$ENDIF}

**Comment by bmitov** [comment]
Thank you! I have committed the missing file

**Comment by krundt** [comment]
THANKS! I only want to use this package to rotate an image. Seems to work just fine now in my 64 bit environment.
